name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - run: poetry install --with dev
      - run: poetry run flake8 xmasdraw/
      - run: poetry run black --check xmasdraw/
      - run: poetry run isort --check xmasdraw/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - run: poetry install --with dev
      - run: poetry run pytest

  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: redhat-actions/buildah-build@v2
        with:
          image: nautik/xmasdraw
          containerfiles: |
            ./Dockerfile
